### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by jeremieSimon** [mherrmann/java-generator-functions#6]
I really like your implementation of the generators.

Do you think it would be ok to wrap the element computed inside the generator in some kind of LazyElement<T> so that this element could also encapsulate eventual exceptions that happened in the run function. And just like when call future.get in java you might return the execution exception when you would do LazyElement.get()

It would happen to be nice when piping generators together.

**Comment by mherrmann** [comment]
Hi,

thanks for the kind words. `Generator` already encapsulates the eventual exceptions and re-raises them when an element is accessed. If you look at lines 78&79 in `[Generator.java](https://github.com/mherrmann/java-generator-functions/blob/master/src/main/java/io/herrmann/generator/Generator.java)`:

```
if (exceptionRaisedByProducer != null)
    throw exceptionRaisedByProducer;
```

As an alternative, maybe in your own code you could `yield(new LazyElement(...))` to achieve the behaviour you want?

**Comment by jeremieSimon** [comment]
Yes, but I meant, that if there is an exception that is being thrown by the computation of one of the element, then the generator is being stopped.
And I was thinking that it could be handy to wrap the element, inside something that would be either the result or the exception so the rest of the elements from the generator could still be computed (not sure if it's clear).

**Comment by mherrmann** [comment]
I think you can already achieve this yourself:

```
class LazyElement {
    private Integer result = null;
    private RuntimeException exception;
    LazyElement(Integer result) {
        this.result = result;
    }
    LazyElement(RuntimeException exception) {
        this.exception = exception;
    }
    Integer getResult() {
        if (exception != null)
            throw exception;
        return result;
    }
}

Generator<Integer> myGenerator = new Generator<Integer>() {
    public void run() throws InterruptedException {
        try {
            ...
            // Try to yield an element
            yield(new LazyElement(myInteger));
        } catch (RuntimeException e) {
            yield(new LazyElement(e));
        }
    }
};

for (LazyElement element : myGenerator)
    // This raises a RuntimeException if it occurred in the generator:
    Integer intElem = element.getResult();
    System.out.println(intElem);
```
